export const projectDetails = [
  {
    title: "씨네톡 (Cinetalk)",
    description:
      "씨네톡 (Cinetalk)은 영화에 대한 자세한 정보와 사용자 리뷰를 제공하는 서비스입니다. 영화에 대한 키워드, 리뷰로 유저에게 영화를 추천합니다.",
    logoSrc: "/images/logos/cinetalk.png",
    imgSrc: "/images/projects/cinetalk.png",
    gitHub: "https://github.com/Devinix00/cinetalk-front",
    siteUrl: "https://cinetalk-front-dev.vercel.app",
    techStacks: [
      "Next.Js (App router)",
      "Typescript",
      "tailwindcss",
      "React-Query",
      "Zustand",
    ],
    myContributions: [
      "카카오, 네이버 소셜 로그인",
      "상세 페이지 반응형 퍼블리싱",
      "영화 리뷰 등록, 수정, 삭제, 좋아요",
      "영화 리뷰 무한 스크롤 조회",
      "영화 평점 등록",
      "영화 찜하기",
      "영화 키워드 작성",
      "영화 포스터 색상 추출",
    ],
  },
  {
    title: "오늘의 운세",
    description:
      "유저의 생년월일, MBTI를 이용해 운세를 제공하는 모바일 앱입니다. ChatGPT API를 이용하여 유저의 운세 데이터를 받아오며, 유저들에게 오늘의 한마디를 푸시 메세지로 제공합니다.",
    logoSrc: "/images/logos/today_s_horoscope.png",
    imgSrc: "/images/projects/today_s_horoscope.png",
    gitHub: "https://github.com/Devinix00/today-s-horoscope",
    siteUrl: "",
    techStacks: [
      "Turborepo",
      "React-Native (expo)",
      "Firebase Cloud Messaging (FCM)",
      "React",
      "Next.Js (App router) (admin)",
      "Typescript",
      "tailwindcss (admin)",
      "SCSS",
      "React-Query",
      "Zustand",
    ],
    myContributions: [
      "Turborepo를 이용하여 멀티레포 구성",
      "React-Native Webview 구성",
      "Android 물리적 뒤로가기 구현",
      "푸시 메세지 구현",
      "어드민 페이지 개발",
    ],
  },
  {
    title: "모두의 텃밭",
    description:
      "전국의 텃밭을 조회, 등록하고, 분양하는 웹 서비스입니다. 커뮤니티, 지도, 채팅 기능이 포함되어있습니다.",
    logoSrc: "/images/logos/everyone_s_garden.png",
    imgSrc: "/images/projects/everyone_s_garden.png",
    gitHub: "https://github.com/Devinix00/everyone-s-garden-front",
    siteUrl: "https://everyonesgarden-v2.vercel.app",
    techStacks: [
      "React",
      "Typescript",
      "Chakra UI",
      "Axios",
      "React-Query",
      "Zustand",
    ],
    myContributions: [
      "카카오, 네이버 소셜 로그인",
      "지역 검색 (네이버 지도 위치 이동)",
      "네이버 지도 기반 내 위치 (geolocation)",
      "위도와 경도를 조작하여 텃밭 조회",
      "사이드 바 텃밭 무한 스크롤 조회",
      "텃밭 신고, 찜하기, 신청하기",
    ],
  },
  {
    title: "저메추 (DMR)",
    description:
      "유저들에게 저녁 메뉴를 추천해주는 서비스입니다. 유저는 자신의 음식 취향에 대한 질문에 답을하고, 서비스는 이를 토대로 유저에게 저녁 메뉴를 추천합니다.",
    logoSrc: "/images/logos/DMR.png",
    gitHub: "https://github.com/Devinix00/Dinner-Menu-Recommendation",
    siteUrl: "",
    techStacks: [
      "React",
      "Typescript",
      "SCSS",
      "Axios",
      "React-Query",
      "Zustand",
    ],
  },
];
